version: "3"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - gems:/ruby_gems
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "budget"
volumes:
  gems:
