default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: budget_dev
  username: budget

test:
  <<: *default:
  database: budget_test
  username: travis

production:
  <<: *default
  database: budget
  username: budget
