default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: budget_dev
  username: budget
  password: kowkyk-tabru4-rutRyt

test:
  <<: *default
  database: budget_test
  username: budget
  password: kowkyk-tabru4-rutRyt

production:
  <<: *default
  database: budget
  username: budget
