default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: db
  port: 5432
  database: budget
  username: budget

test:
  <<: *default
  database: budget_test
  username: budget
  password: kowkyk-tabru4-rutRyt

production:
  <<: *default
  host: budget-server_db
  database: budget-server
  username: budget-server
